# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
# generate kernel instances to speed up compilation
import os
from dataclasses import dataclass
from typing import ClassVar, List

from codegen.arch import ArchTrait
from codegen.cpp_symbol_map import (
    LAYOUT_MAP,
    BOOL_MAP,
    PIPELINE_MAP,
    PIPELINE_ENUM_MAP,
    MODE_MAP,
    FWD_DTYPE_MAP,
    BIAS_MAP,
    get_mask_cpp_type,
    QSCALE_MAP,
)
from codegen.utils import update_file


DTYPE_BITS = {
    "fp32": 32,
    "fp16": 16,
    "bf16": 16,
    "fp8": 8,
    "fp8bf16": 8,
    "fp8fp32": 8,
    "bf8": 8,
}

K0_MAX_SUBMAX_MAP = {
    32: 32,
    48: 48,
    64: 64,
    80: 96,
    96: 128,
    128: 128,
    192: 192,
    256: 256,
}

SAGEATTENTION_FWD_KERNEL_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.\n
// auto generated by generate.py
#include "ck_tile/ops/fmha/block/variants.hpp"
#include "sageattention_fwd.hpp"
#include "sageattention_fwd_codegen.hpp"
"""

SAGEATTENTION_FWD_KERNEL_BODY_TEMPLATE = """
#include <iostream>

#if !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})

using sageattention_dtype = {F_dtype};

using sageattention_block_tile = ck_tile::sequence<{F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}>;

using sageattention_shape = ck_tile::TileFmhaShape<sageattention_block_tile,
                                          ck_tile::sequence<{F_rm0}, {F_rn0}, {F_rk0}>,
                                          ck_tile::sequence<{F_wm0}, {F_wn0}, {F_wk0}>,
                                          ck_tile::sequence<{F_rm1}, {F_rn1}, {F_rk1}>,
                                          ck_tile::sequence<{F_wm1}, {F_wn1}, {F_wk1}>,
                                          {F_vlayout}>;

using sageattention_traits = ck_tile::TileFmhaTraits<{F_spad},
                                            {F_skpad},
                                            {F_dpad},
                                            {F_dvpad},
                                            {F_logits},
                                            {F_bias},
                                            false,
                                            {F_lse},
                                            {F_dropout},
                                            {F_qscale},
                                            {F_occupancy},
                                            {F_skip},
                                            {F_sink}>;

using sageattention_variant = ck_tile::ComposedAttention<{F_logits} * ck_tile::LOGITS_SOFT_CAP, CK_TILE_FMHA_FWD_FAST_EXP2>;

using sageattention_mask = {F_mask};

using sageattention_pipeline_problem = ck_tile::BlockFmhaPipelineProblem<
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::QDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::KDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::VDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::SaccDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::SMPLComputeDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::BiasDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::RandValOutputDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::LSEDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::PDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::OaccDataType,
    typename SageAttentionFwdTypeConfig<sageattention_dtype>::ODataType,
    sageattention_shape,
    {F_mode},
    sageattention_variant,
    sageattention_mask,
    {F_trload},
    sageattention_traits>;

using sageattention_pipeline = {F_pipeline}<
    sageattention_pipeline_problem>;

using sageattention_epilogue =
    ck_tile::Default2DEpilogue<ck_tile::Default2DEpilogueProblem<typename SageAttentionFwdTypeConfig<sageattention_dtype>::OaccDataType,
                               typename SageAttentionFwdTypeConfig<sageattention_dtype>::ODataType,
                               {F_spad}, {F_dvpad}>>;

using sageattention_kernel = ck_tile::SageAttentionFwdKernel<sageattention_pipeline, sageattention_epilogue>;


using trait = sageattention_fwd_traits_<{F_hdim}, {F_dtype}, {F_mode},{F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}, {F_vlayout},
                        {F_pipeline_enum}, {F_logits}, sageattention_mask, {F_bias}, {F_lse}, {F_dropout}, {F_qscale}, {F_spad}, {F_skpad}, {F_dpad}, {F_dvpad}, {F_trload}, {F_skip}, {F_sink}>;

template<>
float sageattention_fwd_<trait, {F_arch.tag}>(const ck_tile::stream_config& s, sageattention_fwd_args a)
{{
    using k_ = sageattention_kernel;
    if(s.log_level_ > 0)
        std::cout << ", {F_kname}" << std::flush;
    auto [kargs, grids] = make_sageattention_fwd_kargs<k_>(a);
    const dim3 blocks                      = k_::BlockSize();
    constexpr ck_tile::index_t kBlockPerCu = k_::kBlockPerCu;
    return ck_tile::launch_kernel(s, ck_tile::make_kernel<kBlockPerCu, {F_arch.tag}>(k_{{}}, grids, blocks, 0, kargs));
}}

#endif // !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})
"""


@dataclass(frozen=True)
class SageAttentionFwdTrait:
    """Trait for SageAttention forward kernel configuration"""

    hdim: int
    dtype: str
    mode: str  # batch or group
    bm0: int
    bn0: int
    bk0: int
    bn1: int
    bk1: int
    bk0max: int
    vlayout: str  # row or col
    pipeline: str
    logits: str  # t or f (logits soft cap)
    mask: str
    bias: str
    lse: str  # t or f (store LSE)
    dropout: str  # t or f
    qscale: str
    spad: str  # seqlen_q padding
    skpad: str  # seqlen_k padding
    dpad: str  # hdim_q padding
    dvpad: str  # hdim_v padding
    trload: str  # t or f (transpose load)
    skip: str  # t or f (skip min seqlen)
    sink: str  # t or f (has sink tokens)


@dataclass
class SageAttentionFwdFactory:
    """Factory for generating SageAttention forward kernel instances"""

    arch: ArchTrait
    dtype: str
    mode: str
    hdim: int

    # Default tile configurations
    DEFAULT_TILES: ClassVar = {
        32: {"bm0": 128, "bn0": 128, "bk0": 32, "bn1": 32, "bk1": 32},
        64: {"bm0": 128, "bn0": 128, "bk0": 64, "bn1": 64, "bk1": 64},
        128: {"bm0": 128, "bn0": 128, "bk0": 128, "bn1": 128, "bk1": 128},
        256: {"bm0": 128, "bn0": 128, "bk0": 256, "bn1": 128, "bk1": 128},
    }

    def create_trait(self, **overrides) -> SageAttentionFwdTrait:
        """Create a trait with default values and optional overrides"""
        tiles = self.DEFAULT_TILES.get(self.hdim, self.DEFAULT_TILES[128])

        defaults = {
            "hdim": self.hdim,
            "dtype": self.dtype,
            "mode": self.mode,
            "bm0": tiles["bm0"],
            "bn0": tiles["bn0"],
            "bk0": tiles["bk0"],
            "bn1": tiles["bn1"],
            "bk1": tiles["bk1"],
            "bk0max": K0_MAX_SUBMAX_MAP.get(self.hdim, 128),
            "vlayout": "row",
            "pipeline": "qr_async",
            "logits": "f",
            "mask": "no",
            "bias": "no",
            "lse": "f",
            "dropout": "f",
            "qscale": "no",
            "spad": "f",
            "skpad": "f",
            "dpad": "f",
            "dvpad": "f",
            "trload": "f",
            "skip": "f",
            "sink": "f",
        }

        defaults.update(overrides)
        return SageAttentionFwdTrait(**defaults)

    def get_traits(self) -> List[SageAttentionFwdTrait]:
        """Generate list of traits for this configuration"""
        traits = []

        # Basic configurations
        traits.append(self.create_trait())

        # With masking
        traits.append(self.create_trait(mask="generic"))

        # With bias
        traits.append(self.create_trait(bias="bias"))

        # With LSE (for training)
        traits.append(self.create_trait(lse="t"))

        # Combined: mask + bias + lse
        traits.append(self.create_trait(mask="generic", bias="bias", lse="t"))

        return traits


def get_factory(
    target: str, dtype: str = "fp16", mode: str = "batch", hdim: int = 128
) -> SageAttentionFwdFactory:
    """Get factory for a specific target architecture"""
    arch_name = target.split(":")[0]  # e.g., "gfx90a" from "gfx90a:xnack+"
    arch = ArchTrait(name=arch_name)
    return SageAttentionFwdFactory(arch=arch, dtype=dtype, mode=mode, hdim=hdim)


def list_blobs(targets: List[str], optdims: List[int], filters: List[str]) -> List[str]:
    """List all blob filenames that will be generated"""
    blobs = []

    for target in targets:
        arch_name = target.split(":")[0]
        for hdim in optdims:
            for dtype in ["fp16", "bf16"]:
                blob_name = f"sageattention_fwd_{dtype}_h{hdim}_{arch_name}.cpp"
                blobs.append(blob_name)

    return blobs


def write_blobs(
    targets: List[str], output_dir: str, optdims: List[int], filters: List[str]
) -> None:
    """Generate and write all kernel blob files"""
    for target in targets:
        arch_name = target.split(":")[0]
        arch = ArchTrait(name=arch_name)

        for hdim in optdims:
            for dtype in ["fp16", "bf16"]:
                factory = SageAttentionFwdFactory(
                    arch=arch, dtype=dtype, mode="batch", hdim=hdim
                )
                traits = factory.get_traits()

                # Generate kernel code for each trait
                kernel_code = SAGEATTENTION_FWD_KERNEL_HEADER

                for trait in traits:
                    # Format the kernel body template with trait values
                    try:
                        kernel_body = SAGEATTENTION_FWD_KERNEL_BODY_TEMPLATE.format(
                            F_arch=arch,
                            F_dtype=FWD_DTYPE_MAP[dtype],
                            F_bm0=trait.bm0,
                            F_bn0=trait.bn0,
                            F_bk0=trait.bk0,
                            F_bn1=trait.bn1,
                            F_bk1=trait.bk1,
                            F_bk0max=trait.bk0max,
                            F_rm0=1,
                            F_rn0=1,
                            F_rk0=1,  # Default repeat values
                            F_wm0=1,
                            F_wn0=1,
                            F_wk0=1,  # Default warp values
                            F_rm1=1,
                            F_rn1=1,
                            F_rk1=1,
                            F_wm1=1,
                            F_wn1=1,
                            F_wk1=1,
                            F_vlayout=LAYOUT_MAP[trait.vlayout],
                            F_spad=BOOL_MAP[trait.spad],
                            F_skpad=BOOL_MAP[trait.skpad],
                            F_dpad=BOOL_MAP[trait.dpad],
                            F_dvpad=BOOL_MAP[trait.dvpad],
                            F_logits=BOOL_MAP[trait.logits],
                            F_bias=BIAS_MAP[trait.bias],
                            F_lse=BOOL_MAP[trait.lse],
                            F_dropout=BOOL_MAP[trait.dropout],
                            F_qscale=QSCALE_MAP[trait.qscale],
                            F_occupancy=-1,
                            F_skip=BOOL_MAP[trait.skip],
                            F_sink=BOOL_MAP[trait.sink],
                            F_mask=get_mask_cpp_type(trait.mask),
                            F_pipeline=PIPELINE_MAP[trait.pipeline],
                            F_pipeline_enum=PIPELINE_ENUM_MAP[trait.pipeline],
                            F_mode=MODE_MAP[trait.mode],
                            F_trload=BOOL_MAP[trait.trload],
                            F_kname=f"sageattention_fwd_{dtype}_h{hdim}",
                            F_hdim=hdim,
                        )
                        kernel_code += kernel_body
                    except KeyError as e:
                        print(f"Warning: Skipping trait due to missing key: {e}")
                        continue

                # Write to file
                blob_name = f"sageattention_fwd_{dtype}_h{hdim}_{arch_name}.cpp"
                output_path = os.path.join(output_dir if output_dir else ".", blob_name)
                update_file(output_path, kernel_code)
                print(f"Generated: {blob_name}")
