config_dir: /opt/rocprof-compute/libexec/rocprofiler-compute/rocprof_compute_soc/analysis_configs
device: -1
dispatch: null
filter_blocks: {}
format_rocprof_output: csv
hip_trace: false
join_type: grid
kernel: null
kernel_names: false
kokkos_trace: false
list_metrics: null
loglevel: 20
lucky: false
mem_level: ALL
mode: profile
name: ttest
no_roof: false
path: /mydata/sourcecode/composable_kernel/workloads/ttest/MI308X
pc_sampling_interval: 1
quiet: false
remaining:
- --
- ./build/bin/tile_example_fmha_fwd
- -init=0
- -b=1
- -s=4800
- -h=16
- -h_k=1
- -d=72
- -prec=bf16
- -vlayout=r
- -qscale=0
- -kname=1
- -mode=1
- -v=1
- -operm=1
- -iperm=1
rocprofiler_sdk_library_path: /opt/rocm/lib/librocprofiler-sdk.so
roof_only: false
roofline_data_type:
- FP32
sort: kernels
spatial_multiplexing: null
specs: false
subpath: gpu
summaries: false
target: null
use_rocscope: false
verbose: 0
